Repository readmeio/syntax-highlighter, pull requests merged in 2020-10, with the labels that each got.

#21 fix(readonly): wip styled output
  public/index.js
  src/codeMirror/index.jsx
Labels: type:bug

#22 feat(context): exporting context provider
  public/index.js
  src/codeMirror/index.jsx
  src/index.js
Labels: type:enhancement

#24 chore: moving react and react-dom into being peerdeps
  package-lock.json
  package.json
Labels: scope:dependency

#23 fix: check for \n in CodeMirror runmode
  __tests__/codeMirror.test.js
  src/codeMirror/index.jsx
Labels: type:bug

#26 feat: adding support for TOML highlighting
  README.md
  __tests__/__fixtures__/toml/index.js
  __tests__/__fixtures__/toml/sample.toml
  __tests__/__snapshots__/codeMirror.test.js.snap
  src/utils/cm-mode-imports.js
Labels: type:enhancement
